apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  selector:
    app: auth-server
  ports:
    - name: http
      port: 80
      targetPort: 80
    - port: 4004
      name: http-mgm
      targetPort: 4004